# fly.toml app configuration file generated for xp-tracker on 2025-01-27T17:04:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xp-tracker'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.22.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1GB'
